version: "3.5"

services:
  db:
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=carDB
    image: postgres:16.2-alpine3.19
    ports:
      - "5433:5432"
  app:
    image: car_catalog:latest
    ports:
      - "8000:8000"
    depends_on:
      - db
    restart: on-failure